CARNET="201612218"
REPO_CODE="https://github.com/susanpamela2520/Pr-cticas-SA-B-201612218"
REPO_GITOPS="https://github.com/susanpamela2520/Pr-cticas-SA-B-201612218-gitops"
APP="sa-platform-gateway"
NS="sa-prod"
IMAGE="ghcr.io/susanpamela2520/pr-cticas-sa-b-201612218/api-gateway:v1.1.9"

COSIGN_IDENTITY_REGEXP="https://github.com/susanpamela2520/Pr-cticas-SA-B-201612218/.*"
COSIGN_ISSUER="https://token.actions.githubusercontent.com"